# Generated by Django 5.0.6 on 2024-08-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='punctuality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
