# Generated by Django 5.0.6 on 2024-08-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0002_alter_course_courseid_alter_student_punctuality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
